### ISSUE TITLE
Preparing new submission to CRAN

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/r5r#244]
- [x] upgrade R5 to version 6.7
- [x] document and test new function: pareto frontier. #241 
- [x] document and test new function: set fare rules. #242 
- [x] create vignette of pareto frontier
- [x] ~document and test new function: set road speed. #187~ This is on hold for a future version.
- [x] replace custom elevation calculations with R5's native feature #243 and #233 
- [x] finish fare calculator vignette #245 
- [x] decide on the behaviour of `travel_time_matrix()` when `breakdown = T`, and update its documentation accordingly #247 
- [x] calculate accessibility to multiple opportunities at once #218 
- [x] add level of traffic stress values to output of `street_network_to_sf()` #251 
- [x] return accessibility results as floating point values #235 
- [x] create new vignette about time window parameter #120

**Comment by rafapereirabr** [comment]
Package submitted to CRAN

**Comment by rafapereirabr** [comment]
CRAN got back to us with the following errors

> 
> package r5r_1.0.0.tar.gz does not pass the incoming checks automatically, please see the following pre-tests:
> Windows: <https://win-builder.r-project.org/incoming_pretest/r5r_1.0.0_20230127_023612/Windows/00check.log>
> Status: 1 ERROR, 1 WARNING, 2 NOTEs
> Debian: <https://win-builder.r-project.org/incoming_pretest/r5r_1.0.0_20230127_023612/Debian/00check.log>
> Status: 3 ERRORs, 1 WARNING, 2 NOTEs
> 
> Last released version's CRAN status: OK: 12
> See: <https://cran.r-project.org/web/checks/check_results_r5r.html>

**Comment by rafapereirabr** [comment]
Fixed and resubmitted

**Comment by rafapereirabr** [comment]
on its way to CRAN
